# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "example-console"
version = "0.0.0"
publish = false
authors = ["MaulingMonkey <git@maulingmonkey.com>"]
edition = "2018"

[dependencies]
lies = { path = "../lies", version = "=0.0.2" }
